#ifndef SIGTOOL_MAGIC_NUMBERS_H
#define SIGTOOL_MAGIC_NUMBERS_H

namespace SigTool {

enum {
    CS_ADHOC = 0x00000002,
    CS_HARD = 0x00000100,
    CS_KILL = 0x00000200,
    CS_CHECK_EXPIRATION = 0x00000400,
    CS_RESTRICT = 0x00000800,
    CS_ENFORCEMENT = 0x00001000,
    CS_REQUIRE_LV = 0x00002000,
    CS_RUNTIME = 0x00010000,

    // Option flag bits Apple's codesign carries over verbatim for
    // --preserve-metadata=flags.
    CS_PRESERVABLE_FLAGS = CS_HARD | CS_KILL | CS_CHECK_EXPIRATION
                           | CS_RESTRICT | CS_ENFORCEMENT | CS_REQUIRE_LV
                           | CS_RUNTIME,
};

enum {
    CSMAGIC_EMBEDDED_SIGNATURE = 0xfade0cc0,
    CSMAGIC_CODEDIRECTORY = 0xfade0c02,
    CSMAGIC_REQUIREMENTS = 0xfade0c01,
    CSMAGIC_EMBEDDED_ENTITLEMENTS = 0xfade7171,
    CSMAGIC_EMBEDDED_ENTITLEMENTS_DER = 0xfade7172,
    CSMAGIC_BLOBWRAPPER = 0xfade0b01,
};

enum {
    CS_EXECSEG_MAIN_BINARY = 0x1,
};

enum {
    CS_HASHTYPE_SHA256 = 2,
};

enum CSSlot {
    CSSLOT_CODEDIRECTORY = 0,
    CSSLOT_REQUIREMENTS = 2,
    CSSLOT_ENTITLEMENTS = 5,
    CSSLOT_ENTITLEMENTS_DER = 7,
    CSSLOT_SIGNATURESLOT = 0x10000,
};
};

#endif
